/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit telemetry event
         * @description Submit a real-time telemetry event from Claude Code agent
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TelemetryEvent"];
                };
            };
            responses: {
                /** @description Event recorded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TelemetryResponse"];
                    };
                };
                /** @description Invalid event data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregated dashboard statistics
         * @description Retrieve comprehensive statistics across all projects
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project name */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Get system health status and diagnostics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example healthy */
                            status?: string;
                            uptime?: number;
                            checks?: {
                                /** @enum {string} */
                                database?: "healthy" | "unhealthy";
                                /** @enum {string} */
                                telemetry_bridge?: "healthy" | "unhealthy";
                                /** @enum {string} */
                                file_watcher?: "healthy" | "unhealthy";
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TelemetryEvent: {
            /**
             * @description Agent identifier
             * @example code-editor
             */
            agent: string;
            /**
             * @description Event type
             * @example file_edit
             */
            event: string;
            /**
             * @description Event message
             * @example Edited file.js
             */
            message: string;
            /**
             * @description Related file path
             * @example src/app.js
             */
            file?: string;
            /**
             * @description Number of lines changed
             * @example 42
             */
            lines_changed?: number;
            /**
             * @description Operation duration
             * @example 1500
             */
            duration_ms?: number;
            /** @description Additional metadata */
            metadata?: Record<string, never>;
        };
        TelemetryResponse: {
            success?: boolean;
            event_id?: number;
            session_id?: string;
            project?: string;
        };
        DashboardStats: {
            /** @description Total events across all projects */
            total_events?: number;
            /** @description Total unique files touched */
            total_files?: number;
            /** @description Number of active agents */
            total_agents?: number;
            /** @description Total lines of code changed */
            total_lines_changed?: number;
            /** @description Number of active sessions */
            active_sessions?: number;
            /** @description Server uptime */
            uptime_seconds?: number;
        };
        Project: {
            /** @example raven */
            name?: string;
            /** @example /Users/seth/projects/raven */
            path?: string;
            active?: boolean;
            /** Format: date-time */
            lastActivity?: string;
        };
        Error: {
            /** @description Error message */
            error?: string;
            /** @description HTTP status code */
            statusCode?: number;
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
