/**
 * Typed API helpers — proof-of-pattern for using the generated OpenAPI types.
 *
 * `api-types.d.ts` is generated by `npm run openapi:gen` (frontend) from
 * `backend/config/openapi.json`. These helpers re-export schema shapes via
 * JSDoc imports so callers can `@type` annotations without each file having
 * to know the path indexing dance into `paths[...].responses[...].content`.
 *
 * Add new wrappers here as you adopt typed responses across the frontend.
 */

import { apiFetch } from './apiClient.js';

/**
 * @typedef {import('./api-types.d.ts').components['schemas']} ApiSchemas
 *
 * @typedef {ApiSchemas['DashboardStats']} DashboardStats
 * @typedef {ApiSchemas['Project']} Project
 * @typedef {ApiSchemas['TelemetryEvent']} TelemetryEvent
 * @typedef {ApiSchemas['TelemetryResponse']} TelemetryResponse
 */

/**
 * Fetch dashboard stats with the generated response type attached.
 * @returns {Promise<DashboardStats>}
 */
export async function fetchDashboardStats() {
  return /** @type {DashboardStats} */ (await apiFetch('/dashboard-stats'));
}

/**
 * Fetch the configured projects list.
 * @returns {Promise<{ projects: Project[]; basePath: string; autoDiscover: boolean }>}
 */
export async function fetchProjects() {
  return apiFetch('/projects');
}
